name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: vuepress-deploy
      uses: immense/immybot-documentation@main
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: docs/.vuepress/dist # The folder, the action should deploy.
        BUILD_SCRIPT: yarn && yarn build
        TARGET_REPO: immense/immybot-documentation
        TARGET_BRANCH: gh_pages
